// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsEwXrmyE0_uqqLXQmsQSCUgWFD80rNdM',
    appId: '1:927928925170:web:10347cc3d3cc40034f096b',
    messagingSenderId: '927928925170',
    projectId: 'ecommerce1-c697f',
    authDomain: 'ecommerce1-c697f.firebaseapp.com',
    storageBucket: 'ecommerce1-c697f.appspot.com',
    measurementId: 'G-4X2HF6YBX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGbfo7mb38GONVIQMiOwgmzl51dVXavXw',
    appId: '1:927928925170:android:44512385376e94fa4f096b',
    messagingSenderId: '927928925170',
    projectId: 'ecommerce1-c697f',
    storageBucket: 'ecommerce1-c697f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCisYn2yTblBpbVyoXWWDFHs1zgTQDdPek',
    appId: '1:927928925170:ios:664e1eef3ca0ed9d4f096b',
    messagingSenderId: '927928925170',
    projectId: 'ecommerce1-c697f',
    storageBucket: 'ecommerce1-c697f.appspot.com',
    iosBundleId: 'com.example.listeCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCisYn2yTblBpbVyoXWWDFHs1zgTQDdPek',
    appId: '1:927928925170:ios:65fda16d2289724f4f096b',
    messagingSenderId: '927928925170',
    projectId: 'ecommerce1-c697f',
    storageBucket: 'ecommerce1-c697f.appspot.com',
    iosBundleId: 'com.example.listeCourse.RunnerTests',
  );
}
